name: MySQL-Tokens
main: me.bukkit.mTokens.Inkzzz.Tokens
version: 1.0
author: [ Inkzzz ]
commands:
  tokens:
    description: Tokens Commands!

permissions:
  tokens.admin:
    description: Allows player to take and give tokens!
  tokens.reset:
    description: Allows the player reset tokens!